version: '3.8'

services:
  todo-app:
    image: node:18-alpine
    container_name: todo-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

volumes:
  node_modules:
